/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.ucr.if3000.biblioteca.gui;

/**
 *
 * @author ValeriaLeivaQuirós
 */
public class MenuBibliotecologo extends javax.swing.JFrame {

    /**
     * Creates new form MenuBibliotecologo
     */
    public MenuBibliotecologo() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuLibro = new javax.swing.JMenu();
        jMenuAgregar = new javax.swing.JMenu();
        jMenuItemLibro = new javax.swing.JMenuItem();
        jMenuItemRevista = new javax.swing.JMenuItem();
        Tesis = new javax.swing.JMenuItem();
        jMenuItemPeriodico = new javax.swing.JMenuItem();
        jMenuItemMemoria = new javax.swing.JMenuItem();
        jMenuItemOtro = new javax.swing.JMenuItem();
        jMenuItemMantenimientoCtalogo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuAutores = new javax.swing.JMenu();
        jMenuItemRegistrarAutor = new javax.swing.JMenuItem();
        jMenuItemMantemientoAutores = new javax.swing.JMenuItem();
        jMenuEmpleados = new javax.swing.JMenu();
        jMenuItemRegistrarEmpleado = new javax.swing.JMenuItem();
        jMenuItemMantenimientoEmpleado = new javax.swing.JMenuItem();
        jMenuUsuarios = new javax.swing.JMenu();
        jMenuItemRegistrarUsuario = new javax.swing.JMenuItem();
        jMenuItemMantenimientoUsuarios = new javax.swing.JMenuItem();
        jMenuItemUsuariosMorosos = new javax.swing.JMenuItem();
        jMenuPrestamos = new javax.swing.JMenu();
        jMenuItemRegistrarPrestamo = new javax.swing.JMenuItem();
        jMenuItemMostrarLibrosPrestados = new javax.swing.JMenuItem();
        jMenuBuscar = new javax.swing.JMenu();
        jMenuItemBuscarUsuario = new javax.swing.JMenuItem();
        jMenuItemBuscarObra = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuSalir = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));

        jMenuLibro.setForeground(new java.awt.Color(0, 51, 255));
        jMenuLibro.setText("Libros");
        jMenuLibro.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N

        jMenuAgregar.setForeground(new java.awt.Color(0, 51, 255));
        jMenuAgregar.setText("Agregar");
        jMenuAgregar.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N

        jMenuItemLibro.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jMenuItemLibro.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItemLibro.setText("Libro");
        jMenuItemLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLibroActionPerformed(evt);
            }
        });
        jMenuAgregar.add(jMenuItemLibro);

        jMenuItemRevista.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jMenuItemRevista.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItemRevista.setText("Revista");
        jMenuItemRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRevistaActionPerformed(evt);
            }
        });
        jMenuAgregar.add(jMenuItemRevista);

        Tesis.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        Tesis.setForeground(new java.awt.Color(0, 51, 255));
        Tesis.setText("Tesis");
        Tesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TesisActionPerformed(evt);
            }
        });
        jMenuAgregar.add(Tesis);

        jMenuItemPeriodico.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jMenuItemPeriodico.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItemPeriodico.setText("Periodico");
        jMenuItemPeriodico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPeriodicoActionPerformed(evt);
            }
        });
        jMenuAgregar.add(jMenuItemPeriodico);

        jMenuItemMemoria.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jMenuItemMemoria.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItemMemoria.setText("Memoria");
        jMenuItemMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMemoriaActionPerformed(evt);
            }
        });
        jMenuAgregar.add(jMenuItemMemoria);

        jMenuItemOtro.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jMenuItemOtro.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItemOtro.setText("Otro");
        jMenuItemOtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOtroActionPerformed(evt);
            }
        });
        jMenuAgregar.add(jMenuItemOtro);

        jMenuLibro.add(jMenuAgregar);

        jMenuItemMantenimientoCtalogo.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jMenuItemMantenimientoCtalogo.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItemMantenimientoCtalogo.setText("Mantenimiento Catalogo");
        jMenuItemMantenimientoCtalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMantenimientoCtalogoActionPerformed(evt);
            }
        });
        jMenuLibro.add(jMenuItemMantenimientoCtalogo);

        jMenuBar1.add(jMenuLibro);
        jMenuBar1.add(jMenu2);

        jMenuAutores.setForeground(new java.awt.Color(0, 51, 255));
        jMenuAutores.setText("Autores");
        jMenuAutores.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N

        jMenuItemRegistrarAutor.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jMenuItemRegistrarAutor.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItemRegistrarAutor.setText("Registrar Autor");
        jMenuItemRegistrarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarAutorActionPerformed(evt);
            }
        });
        jMenuAutores.add(jMenuItemRegistrarAutor);

        jMenuItemMantemientoAutores.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jMenuItemMantemientoAutores.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItemMantemientoAutores.setText("Mantenimiento Autores");
        jMenuItemMantemientoAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMantemientoAutoresActionPerformed(evt);
            }
        });
        jMenuAutores.add(jMenuItemMantemientoAutores);

        jMenuBar1.add(jMenuAutores);

        jMenuEmpleados.setForeground(new java.awt.Color(0, 51, 255));
        jMenuEmpleados.setText("Empleados");
        jMenuEmpleados.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N

        jMenuItemRegistrarEmpleado.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jMenuItemRegistrarEmpleado.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItemRegistrarEmpleado.setText("Registrar Empleado");
        jMenuItemRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarEmpleadoActionPerformed(evt);
            }
        });
        jMenuEmpleados.add(jMenuItemRegistrarEmpleado);

        jMenuItemMantenimientoEmpleado.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jMenuItemMantenimientoEmpleado.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItemMantenimientoEmpleado.setText("Mantenimiento Empleado");
        jMenuItemMantenimientoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMantenimientoEmpleadoActionPerformed(evt);
            }
        });
        jMenuEmpleados.add(jMenuItemMantenimientoEmpleado);

        jMenuBar1.add(jMenuEmpleados);

        jMenuUsuarios.setForeground(new java.awt.Color(0, 51, 255));
        jMenuUsuarios.setText("Usuarios");
        jMenuUsuarios.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N

        jMenuItemRegistrarUsuario.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jMenuItemRegistrarUsuario.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItemRegistrarUsuario.setText("Registrar Usuario");
        jMenuItemRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarUsuarioActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemRegistrarUsuario);

        jMenuItemMantenimientoUsuarios.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jMenuItemMantenimientoUsuarios.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItemMantenimientoUsuarios.setText("Mantenimiento Usuarios");
        jMenuItemMantenimientoUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMantenimientoUsuariosActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemMantenimientoUsuarios);

        jMenuItemUsuariosMorosos.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jMenuItemUsuariosMorosos.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItemUsuariosMorosos.setText("Mostrar Usuarios Morosos");
        jMenuItemUsuariosMorosos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuariosMorososActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemUsuariosMorosos);

        jMenuBar1.add(jMenuUsuarios);

        jMenuPrestamos.setForeground(new java.awt.Color(0, 51, 255));
        jMenuPrestamos.setText("Prestamos");
        jMenuPrestamos.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N

        jMenuItemRegistrarPrestamo.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jMenuItemRegistrarPrestamo.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItemRegistrarPrestamo.setText("Registrar Prestamo");
        jMenuItemRegistrarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarPrestamoActionPerformed(evt);
            }
        });
        jMenuPrestamos.add(jMenuItemRegistrarPrestamo);

        jMenuItemMostrarLibrosPrestados.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jMenuItemMostrarLibrosPrestados.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItemMostrarLibrosPrestados.setText("Mostrar Libros Prestados");
        jMenuItemMostrarLibrosPrestados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMostrarLibrosPrestadosActionPerformed(evt);
            }
        });
        jMenuPrestamos.add(jMenuItemMostrarLibrosPrestados);

        jMenuBar1.add(jMenuPrestamos);

        jMenuBuscar.setForeground(new java.awt.Color(0, 51, 255));
        jMenuBuscar.setText("Buscar");
        jMenuBuscar.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N

        jMenuItemBuscarUsuario.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jMenuItemBuscarUsuario.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItemBuscarUsuario.setText("Buscar Usuario");
        jMenuItemBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBuscarUsuarioActionPerformed(evt);
            }
        });
        jMenuBuscar.add(jMenuItemBuscarUsuario);

        jMenuItemBuscarObra.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jMenuItemBuscarObra.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItemBuscarObra.setText("Buscar Obra");
        jMenuItemBuscarObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBuscarObraActionPerformed(evt);
            }
        });
        jMenuBuscar.add(jMenuItemBuscarObra);

        jMenuBar1.add(jMenuBuscar);
        jMenuBar1.add(jMenu14);

        jMenuSalir.setForeground(new java.awt.Color(0, 51, 255));
        jMenuSalir.setText("Salir");
        jMenuSalir.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem2.setText("Cerrar Sesion");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuSalir.add(jMenuItem2);

        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLibroActionPerformed
        AgregarLibro agregarLibro = new AgregarLibro();
        agregarLibro.setVisible(true);
        dispose();

    }//GEN-LAST:event_jMenuItemLibroActionPerformed

    private void jMenuItemRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRevistaActionPerformed
        AgregarRevista agregarRevista = new AgregarRevista();
        agregarRevista.setVisible(true);
        dispose();

    }//GEN-LAST:event_jMenuItemRevistaActionPerformed

    private void TesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TesisActionPerformed
        AgregarTesis agregarTesis = new AgregarTesis();
        agregarTesis.setVisible(true);
        dispose();

    }//GEN-LAST:event_TesisActionPerformed

    private void jMenuItemPeriodicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPeriodicoActionPerformed
        AgregarPeriodico agregarPeriodico = new AgregarPeriodico();
        agregarPeriodico.setVisible(true);
        dispose();

    }//GEN-LAST:event_jMenuItemPeriodicoActionPerformed

    private void jMenuItemMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMemoriaActionPerformed
        AgregarMemoria agregarMemoria = new AgregarMemoria();
        agregarMemoria.setVisible(true);
        dispose();

    }//GEN-LAST:event_jMenuItemMemoriaActionPerformed

    private void jMenuItemOtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOtroActionPerformed
        AgregarOtro agregarOtro = new AgregarOtro();
        agregarOtro.setVisible(true);
        dispose();

    }//GEN-LAST:event_jMenuItemOtroActionPerformed

    private void jMenuItemRegistrarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarAutorActionPerformed
        AgregarUsuario agregarUsuario = new AgregarUsuario("autorMenu");
        agregarUsuario.setVisible(true);
        dispose();

    }//GEN-LAST:event_jMenuItemRegistrarAutorActionPerformed

    private void jMenuItemRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarEmpleadoActionPerformed
        AgregarUsuario agregarUsuario = new AgregarUsuario("bibliotecarioMenu");
        agregarUsuario.setVisible(true);
        dispose();

    }//GEN-LAST:event_jMenuItemRegistrarEmpleadoActionPerformed

    private void jMenuItemRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarUsuarioActionPerformed
        AgregarUsuario agregarUsuario = new AgregarUsuario("usuarioMenu");
        agregarUsuario.setVisible(true);
        dispose();

    }//GEN-LAST:event_jMenuItemRegistrarUsuarioActionPerformed

    private void jMenuItemMantenimientoCtalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMantenimientoCtalogoActionPerformed
        OpcionesCatalogo catalogo = new OpcionesCatalogo();
        catalogo.setVisible(true);
        dispose();


    }//GEN-LAST:event_jMenuItemMantenimientoCtalogoActionPerformed

    private void jMenuItemMantemientoAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMantemientoAutoresActionPerformed
        MantenimentoAutores mantenimientAutores = new MantenimentoAutores();
        mantenimientAutores.setVisible(true);
        dispose();

    }//GEN-LAST:event_jMenuItemMantemientoAutoresActionPerformed

    private void jMenuItemMantenimientoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMantenimientoEmpleadoActionPerformed
        MantenimentoBibliotecologos mantenimentoBibliotecologos = new MantenimentoBibliotecologos();
        mantenimentoBibliotecologos.setVisible(true);

        dispose();
    }//GEN-LAST:event_jMenuItemMantenimientoEmpleadoActionPerformed

    private void jMenuItemMantenimientoUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMantenimientoUsuariosActionPerformed
        MantenimentoUsuarios mantenimentoUsuarios = new MantenimentoUsuarios();
        mantenimentoUsuarios.setVisible(true);
        dispose();

    }//GEN-LAST:event_jMenuItemMantenimientoUsuariosActionPerformed

    private void jMenuItemRegistrarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarPrestamoActionPerformed
        RegistrarPrestamo registrarPrestamo = new RegistrarPrestamo();
        registrarPrestamo.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemRegistrarPrestamoActionPerformed

    private void jMenuItemMostrarLibrosPrestadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMostrarLibrosPrestadosActionPerformed
        LibrosPrestados librosPrestados = new LibrosPrestados("MenuBibliotecologo");
        librosPrestados.setVisible(true);
        dispose();

    }//GEN-LAST:event_jMenuItemMostrarLibrosPrestadosActionPerformed

    private void jMenuItemUsuariosMorososActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuariosMorososActionPerformed
        MostrarUsuariosMorosos mostrarUsuariosMorosos = new MostrarUsuariosMorosos();
        mostrarUsuariosMorosos.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemUsuariosMorososActionPerformed

    private void jMenuItemBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBuscarUsuarioActionPerformed
        BuscarUsuario buscarUsuario = new BuscarUsuario("MenuBibliotecologo");
        buscarUsuario.setVisible(true);
        dispose();

    }//GEN-LAST:event_jMenuItemBuscarUsuarioActionPerformed

    private void jMenuItemBuscarObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBuscarObraActionPerformed
        BuscarObra buscarObra = new BuscarObra("MenuBibliotecologo");
        buscarObra.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemBuscarObraActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        InicioDeSesion inicioDeSesion = new InicioDeSesion();
        inicioDeSesion.setVisible(true);
        dispose();

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBibliotecologo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBibliotecologo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBibliotecologo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBibliotecologo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuBibliotecologo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Tesis;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenuAgregar;
    private javax.swing.JMenu jMenuAutores;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuBuscar;
    private javax.swing.JMenu jMenuEmpleados;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemBuscarObra;
    private javax.swing.JMenuItem jMenuItemBuscarUsuario;
    private javax.swing.JMenuItem jMenuItemLibro;
    private javax.swing.JMenuItem jMenuItemMantemientoAutores;
    private javax.swing.JMenuItem jMenuItemMantenimientoCtalogo;
    private javax.swing.JMenuItem jMenuItemMantenimientoEmpleado;
    private javax.swing.JMenuItem jMenuItemMantenimientoUsuarios;
    private javax.swing.JMenuItem jMenuItemMemoria;
    private javax.swing.JMenuItem jMenuItemMostrarLibrosPrestados;
    private javax.swing.JMenuItem jMenuItemOtro;
    private javax.swing.JMenuItem jMenuItemPeriodico;
    private javax.swing.JMenuItem jMenuItemRegistrarAutor;
    private javax.swing.JMenuItem jMenuItemRegistrarEmpleado;
    private javax.swing.JMenuItem jMenuItemRegistrarPrestamo;
    private javax.swing.JMenuItem jMenuItemRegistrarUsuario;
    private javax.swing.JMenuItem jMenuItemRevista;
    private javax.swing.JMenuItem jMenuItemUsuariosMorosos;
    private javax.swing.JMenu jMenuLibro;
    private javax.swing.JMenu jMenuPrestamos;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JMenu jMenuUsuarios;
    // End of variables declaration//GEN-END:variables
}
