/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.ucr.if3000.biblioteca.gui;

import static com.sun.org.apache.bcel.internal.Repository.instanceOf;
import cr.ac.ucr.if3000.biblioteca.domain.Biblioteca;
import cr.ac.ucr.if3000.biblioteca.domain.Catalogo;
import cr.ac.ucr.if3000.biblioteca.domain.Libro;
import cr.ac.ucr.if3000.biblioteca.domain.Memoria;
import cr.ac.ucr.if3000.biblioteca.domain.Otros;
import cr.ac.ucr.if3000.biblioteca.domain.Periodico;
import cr.ac.ucr.if3000.biblioteca.domain.Revista;
import cr.ac.ucr.if3000.biblioteca.domain.Tesis;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ValeriaLeivaQuirós
 */
public class OpcionesCatalogo extends javax.swing.JFrame {

    Biblioteca biblioteca;

    /**
     * Creates new form Cátalogo
     */
    public OpcionesCatalogo() {
        DefaultTableModel modelo = new DefaultTableModel();
        biblioteca = new Biblioteca();
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        boolean esSeleccionado = false;
       
        

        modelo.addColumn("codigo");
        modelo.addColumn("Titulo");
        modelo.addColumn("Fecha de Ingreso");
        modelo.addColumn("Autor");

        for (int i = 0; i < biblioteca.getCatalogos().size(); i++) {
            Catalogo catalogo = biblioteca.getCatalogos().get(i);
            modelo.addRow(new Object[]{catalogo.getCodigoCatalogo(), catalogo.getTitulo(), catalogo.getFechaIngreso(), catalogo.getAutor()});
            this.jTableListaCatalogo.setModel(modelo);

        }
        
//         while(esSeleccionado==true){
//        if(jTableListaCatalogo.addKeyListener(l))
//        seleccionado =  (int) jTableListaCatalogo.getValueAt(jTableListaCatalogo.getSelectedRow(), 0);
//        jTextArea1.setText(biblioteca.buscaCatalogoPorCodigo(seleccionado));
//          esSeleccionado=true;
//            while(esSeleccionado ==true){
//         
//                seleccionado = jTableListaCatalogo.getAccessibleContext();
//                
//    }
    
        jTableListaCatalogo.addMouseListener(new MouseAdapter() {
         public void mousePressed(MouseEvent me) { 
        int seleccionado =  (int) jTableListaCatalogo.getValueAt(jTableListaCatalogo.getSelectedRow(), 0);
       jTextArea1.setText(biblioteca.buscaCatalogoPorCodigo(seleccionado));
         }
        });
    }

    
//    public void keyPressed(KeyEvent e){
//       int seleccionado =  (int) jTableListaCatalogo.getValueAt(jTableListaCatalogo.getSelectedRow(), 0);
//       jTextArea1.setText(biblioteca.buscaCatalogoPorCodigo(seleccionado));
//}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMantenimientoCatalogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaCatalogo = new javax.swing.JTable();
        jComboBoxAgregar = new javax.swing.JComboBox<>();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mantenimiento Catálogo");

        jLabelMantenimientoCatalogo.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabelMantenimientoCatalogo.setForeground(new java.awt.Color(0, 51, 255));
        jLabelMantenimientoCatalogo.setText("Mantenimiento Catálogo");

        jTableListaCatalogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        jTableListaCatalogo.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jTableListaCatalogo.setForeground(new java.awt.Color(0, 51, 255));
        jTableListaCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Tipo", "Titulo", "Autor", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jTableListaCatalogo);

        jComboBoxAgregar.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jComboBoxAgregar.setForeground(new java.awt.Color(0, 51, 255));
        jComboBoxAgregar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agregar Libro", "Agregar Revista", "Agregar Tesis", "Agregar Periódico", "Agregar Memoria", "Agregar Otro" }));
        jComboBoxAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAgregarActionPerformed(evt);
            }
        });

        jButtonModificar.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jButtonModificar.setForeground(new java.awt.Color(0, 51, 255));
        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonEliminar.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(0, 21, 255));
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonAgregar.setForeground(new java.awt.Color(51, 51, 255));
        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/ucr/if3000/biblioteca/Imagenes/sign-out.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(0, 102, 102));
        jTextArea1.setRows(5);
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 102, 102));
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelMantenimientoCatalogo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabelMantenimientoCatalogo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEliminar)
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAgregarActionPerformed

    }//GEN-LAST:event_jComboBoxAgregarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        int seleccionado = (int) jTableListaCatalogo.getValueAt(jTableListaCatalogo.getSelectedRow(), 0);
        Catalogo catalogo = null;
        boolean encontrado = false;
        int cont = 0;
        while (!encontrado) {
            catalogo = biblioteca.getCatalogos().get(cont);
            if (seleccionado == catalogo.getCodigoCatalogo()) {
                encontrado = true;
            }
            cont++;
        }

        if (catalogo instanceof Libro) {
            ModificarLibro modificarLibro = new ModificarLibro(catalogo);
            modificarLibro.setVisible(true);
        } else if (catalogo instanceof Revista) {
            ModificarRevista modificarRevista = new ModificarRevista(catalogo);
            modificarRevista.setVisible(true);
        } else if (catalogo instanceof Tesis) {
            ModificarTesis modificarTesis = new ModificarTesis(catalogo);
            modificarTesis.setVisible(true);
        } else if (catalogo instanceof Periodico) {
            ModificarPeriodico modificarPeriodico = new ModificarPeriodico(catalogo);
            modificarPeriodico.setVisible(true);
        } else if (catalogo instanceof Memoria) {
            ModificarMemoria modificarMemoria = new ModificarMemoria(catalogo);
            modificarMemoria.setVisible(true);
        } else if (catalogo instanceof Otros) {
            ModificarOtro modificarOtro = new ModificarOtro(catalogo);
            modificarOtro.setVisible(true);
        }
        dispose();

    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        int seleccionado = (int) jTableListaCatalogo.getValueAt(jTableListaCatalogo.getSelectedRow(), 0);
        biblioteca.suprimirCatalogo(seleccionado);
        dispose();
        OpcionesCatalogo catalogo = new OpcionesCatalogo();
        catalogo.setVisible(true);
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        String seleccion = jComboBoxAgregar.getItemAt(jComboBoxAgregar.getSelectedIndex());

        if (seleccion.equalsIgnoreCase("Agregar Libro")) {
            AgregarLibro agregarLibro = new AgregarLibro();
            agregarLibro.setVisible(true);
        } else if (seleccion.equalsIgnoreCase("Agregar Revista")) {
            AgregarRevista agregarRevista = new AgregarRevista();
            agregarRevista.setVisible(true);
        } else if (seleccion.equalsIgnoreCase("Agregar Tesis")) {
            AgregarTesis agregarTesis = new AgregarTesis();
            agregarTesis.setVisible(true);
        } else if (seleccion.equalsIgnoreCase("Agregar Periódico")) {
            AgregarPeriodico agregarPeriodico = new AgregarPeriodico();
            agregarPeriodico.setVisible(true);
        } else if (seleccion.equalsIgnoreCase("Agregar Memoria")) {
            AgregarMemoria agregarMemoria = new AgregarMemoria();
            agregarMemoria.setVisible(true);
        } else if (seleccion.equalsIgnoreCase("Agregar Otro")) {
            AgregarOtro agregarOtro = new AgregarOtro();
            agregarOtro.setVisible(true);
        }
        dispose();
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MenuBibliotecologo menuBibliotecologo = new MenuBibliotecologo();
        menuBibliotecologo.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionesCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionesCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionesCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionesCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionesCatalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JComboBox<String> jComboBoxAgregar;
    private javax.swing.JLabel jLabelMantenimientoCatalogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableListaCatalogo;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
