/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.ucr.if3000.biblioteca.gui;

import cr.ac.ucr.if3000.biblioteca.domain.Biblioteca;
import cr.ac.ucr.if3000.biblioteca.domain.Catalogo;
import cr.ac.ucr.if3000.biblioteca.domain.Libro;
import cr.ac.ucr.if3000.biblioteca.domain.Persona;
import cr.ac.ucr.if3000.biblioteca.domain.Prestamo;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.DatePicker;

/**
 *
 * @author ValeriaLeivaQuirós
 */
public class RegistrarPrestamo extends javax.swing.JFrame {

    Biblioteca biblioteca;
    Catalogo catalogoPrestar;
    Persona persona;
    int codigoCatalogo;
    int codigoLibro;
    String identificacionPersona;

    public RegistrarPrestamo() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        biblioteca = new Biblioteca();

        jLabelNumerodePrestamos1.setText(biblioteca.getCodigoPrestamo());

        jButtonUsuario.setVisible(false);
    }

    public RegistrarPrestamo(int cod) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        biblioteca = new Biblioteca();
        codigoCatalogo = cod;

        jLabelNumerodePrestamos1.setText(biblioteca.getCodigoPrestamo());
        catalogoPrestar = biblioteca.buscarLibroPorCodigo((cod));
        jLabelLcodLibro.setText(String.valueOf(catalogoPrestar.getCodigoCatalogo()));
        jLabelTituloLibro.setText(catalogoPrestar.getTitulo());

    }

    RegistrarPrestamo(int codigoLibro, String identificacion) {

        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        biblioteca = new Biblioteca();
        codigoLibro = codigoLibro;
        identificacionPersona = identificacion;

        jLabelNumerodePrestamos1.setText(biblioteca.getCodigoPrestamo());
        catalogoPrestar = biblioteca.buscarLibroPorCodigo((codigoLibro));
        jLabelLcodLibro.setText(String.valueOf(catalogoPrestar.getCodigoCatalogo()));
        jLabelTituloLibro.setText(catalogoPrestar.getTitulo());

        persona = biblioteca.buscarPersonaPorIdentificacion(identificacion);

        jLabelIdentificacionPersona.setText(persona.getIdentificacion());
        jLabelNombreUsuario.setText(persona.getNombreUnico());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelRegistrarPrestamo = new javax.swing.JLabel();
        jLabelNumerodePrestamos = new javax.swing.JLabel();
        jLabelTituloLibro = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelFechaInicioPrestamo = new javax.swing.JLabel();
        jLabelFechaDevolucion = new javax.swing.JLabel();
        jButtonRegistrarPrestamo = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jDateChooserFechaDevolucion = new com.toedter.calendar.JDateChooser();
        jButtonBuscarLibro = new javax.swing.JButton();
        jButtonUsuario = new javax.swing.JButton();
        jLabelNumerodePrestamos1 = new javax.swing.JLabel();
        jDateChooserFechaPrestamo = new com.toedter.calendar.JDateChooser();
        jLabelLibro1 = new javax.swing.JLabel();
        jLabelNombreUsuario = new javax.swing.JLabel();
        jLabelLcodLibro = new javax.swing.JLabel();
        jLabelIdentificacionPersona = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar Préstamo");

        jLabelRegistrarPrestamo.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabelRegistrarPrestamo.setForeground(new java.awt.Color(0, 51, 255));
        jLabelRegistrarPrestamo.setText("Registrar Préstamo");

        jLabelNumerodePrestamos.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabelNumerodePrestamos.setForeground(new java.awt.Color(0, 51, 255));
        jLabelNumerodePrestamos.setText("N° de préstamos:");

        jLabelTituloLibro.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabelTituloLibro.setForeground(new java.awt.Color(0, 51, 255));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("Usuario:");

        jLabelFechaInicioPrestamo.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabelFechaInicioPrestamo.setForeground(new java.awt.Color(0, 51, 255));
        jLabelFechaInicioPrestamo.setText("Fecha inicio de Prestamo:");

        jLabelFechaDevolucion.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabelFechaDevolucion.setForeground(new java.awt.Color(0, 51, 255));
        jLabelFechaDevolucion.setText("Fecha devolución:");

        jButtonRegistrarPrestamo.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jButtonRegistrarPrestamo.setForeground(new java.awt.Color(0, 51, 255));
        jButtonRegistrarPrestamo.setText("Registrar Prestamo");
        jButtonRegistrarPrestamo.setBorder(null);
        jButtonRegistrarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarPrestamoActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(0, 51, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jDateChooserFechaDevolucion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));

        jButtonBuscarLibro.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jButtonBuscarLibro.setForeground(new java.awt.Color(0, 51, 255));
        jButtonBuscarLibro.setText("Buscar Libro");
        jButtonBuscarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarLibroActionPerformed(evt);
            }
        });

        jButtonUsuario.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jButtonUsuario.setForeground(new java.awt.Color(0, 51, 255));
        jButtonUsuario.setText("Buscar Usuario");
        jButtonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuarioActionPerformed(evt);
            }
        });

        jLabelNumerodePrestamos1.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabelNumerodePrestamos1.setForeground(new java.awt.Color(0, 51, 255));
        jLabelNumerodePrestamos1.setText("N° de préstamos:");

        jDateChooserFechaPrestamo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));

        jLabelLibro1.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabelLibro1.setForeground(new java.awt.Color(0, 51, 255));
        jLabelLibro1.setText("Libro:");

        jLabelNombreUsuario.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabelNombreUsuario.setForeground(new java.awt.Color(0, 51, 255));

        jLabelLcodLibro.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabelLcodLibro.setForeground(new java.awt.Color(0, 51, 255));

        jLabelIdentificacionPersona.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabelIdentificacionPersona.setForeground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonRegistrarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelFechaDevolucion)
                                .addGap(52, 52, 52)
                                .addComponent(jDateChooserFechaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNumerodePrestamos)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabelLibro1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabelRegistrarPrestamo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabelNumerodePrestamos1))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelLcodLibro)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelFechaInicioPrestamo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jDateChooserFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabelTituloLibro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelNombreUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))))
                                .addComponent(jLabelIdentificacionPersona)))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBuscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabelRegistrarPrestamo)
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumerodePrestamos)
                    .addComponent(jLabelNumerodePrestamos1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTituloLibro)
                    .addComponent(jButtonBuscarLibro)
                    .addComponent(jLabelLibro1)
                    .addComponent(jLabelLcodLibro))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButtonUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreUsuario)
                    .addComponent(jLabelIdentificacionPersona))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelFechaInicioPrestamo)
                    .addComponent(jDateChooserFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFechaDevolucion)
                    .addComponent(jDateChooserFechaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonRegistrarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed

        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonBuscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarLibroActionPerformed
        BuscarObra buscarObra = new BuscarObra();
        buscarObra.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonBuscarLibroActionPerformed

    private void jButtonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuarioActionPerformed
        BuscarUsuario buscarUsuario = new BuscarUsuario(codigoCatalogo);
        buscarUsuario.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonUsuarioActionPerformed

    private void jButtonRegistrarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarPrestamoActionPerformed

        String numeroPrestamo = jLabelNumerodePrestamos1.getText();
        String libroCod = jLabelLcodLibro.getText();
        String personaIdentificacion = jLabelIdentificacionPersona.getText();

        String dia = Integer.toString(jDateChooserFechaPrestamo.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(jDateChooserFechaPrestamo.getCalendar().get(Calendar.MONTH) + 1);
        String año = Integer.toString(jDateChooserFechaPrestamo.getCalendar().get(Calendar.YEAR));
        String fechaInicio = (dia + "-" + mes + "-" + año);

        String dia1 = Integer.toString(jDateChooserFechaPrestamo.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes2 = Integer.toString(jDateChooserFechaPrestamo.getCalendar().get(Calendar.MONTH) + 1);
        String año3 = Integer.toString(jDateChooserFechaPrestamo.getCalendar().get(Calendar.YEAR));

        String fechaFinal = (dia1 + "-" + mes2 + "-" + año3);
        System.out.println(fechaFinal);
        Prestamo prestamo = new Prestamo(Integer.parseInt(numeroPrestamo), biblioteca.buscarPersonaPorIdentificacion(personaIdentificacion), fechaInicio, fechaFinal);

        System.out.println(prestamo.toString());
        System.out.println(libroCod);
        Catalogo libro = new Libro();
        libro = biblioteca.buscarLibroPorCodigo(Integer.parseInt(libroCod));
        System.out.println(libro.toString());

        biblioteca.registrarPrestamo(biblioteca.buscarLibroPorCodigo(Integer.parseInt(libroCod)), prestamo);

        MenuBibliotecologo menuBibliotecologo = new MenuBibliotecologo();
        menuBibliotecologo.setVisible(true);
        dispose();


    }//GEN-LAST:event_jButtonRegistrarPrestamoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RegistrarPrestamo().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarLibro;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonRegistrarPrestamo;
    private javax.swing.JButton jButtonUsuario;
    private com.toedter.calendar.JDateChooser jDateChooserFechaDevolucion;
    private com.toedter.calendar.JDateChooser jDateChooserFechaPrestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelFechaDevolucion;
    private javax.swing.JLabel jLabelFechaInicioPrestamo;
    private javax.swing.JLabel jLabelIdentificacionPersona;
    private javax.swing.JLabel jLabelLcodLibro;
    private javax.swing.JLabel jLabelLibro1;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JLabel jLabelNumerodePrestamos;
    private javax.swing.JLabel jLabelNumerodePrestamos1;
    private javax.swing.JLabel jLabelRegistrarPrestamo;
    private javax.swing.JLabel jLabelTituloLibro;
    // End of variables declaration//GEN-END:variables
}
